### ISSUE TITLE
add border white for Standards

### ISSUE THREAD

**Issue by biigpongsatorn** [gerardreches/vue-qrcode-component#10]
QR Code must have border white for QR code reader.

If the QR has no border that will can't read.

https://en.wikipedia.org/wiki/QR_code#Standards

standard:
![download](https://user-images.githubusercontent.com/10693658/64101634-79945c80-cd98-11e9-9ccd-dd4d632e9d49.png)

vue-qrcode-component
![download (1)](https://user-images.githubusercontent.com/10693658/64101671-8e70f000-cd98-11e9-8be8-a5c4ba7cf548.png)

**Comment by gerardreches** [comment]
Hi @biigpongsatorn ,

I've done some searching about your point, but although it's recommended, I couldn't find any official standard saying that it must be that way. Actually, QR codes can be read without a white border, just notice that the background around the QR code should have enough contrast (placing the QR code on top of some images might not be a good idea):

> The easiest way to add branding power to your code is to add color to it. Your QR code does not have to be standard black and white in order to be scanned. You can embed multiple colors and apply a color gradient without affecting scanability. The only rule of thumb is that the code color should generally be dark and placed against a light-colored background. Make sure the contrast is sufficient, or the code will be difficult to scan.
> 
> A “reversed out” code, where the background is dark and the boxes are light colored, is generally not recommended. Only a small handful of QR code readers can treat such codes as a film negative and properly interpret the data.
>
>![](https://mondrian.mashable.com/wp-content%252Fuploads%252F2011%252F04%252F630QR-Code2.jpg%252Ffull-fit-in__1200x2000.jpg?signature=KDEMygGsc7ago0OgwkWJ4dxdQL8=&source=http%3A%2F%2Fmashable.com)

Source: https://mashable.com/2011/04/18/qr-code-design-tips

Your QR scanner should be even able to scan that complex QR code.

Since the library this component is based on doesn't include a border, I will decide not to add it either.

## **Solution:**

If your QR code is unreadable because it's on top of a darker background or an image, remember that you can treat the component as any other container, so you can add the CSS properties `border` or `padding` + `background-color` to create your custom quiet zone around your QR code.
