### ISSUE TITLE
Dynamic Sizes

### ISSUE THREAD

**Issue by quanc** [gerardreches/vue-qrcode-component#11]
Is there a way to size a vue-qrcode based on a percentage of a div instead of a fixed pixel size?

**Comment by gerardreches** [comment]
Hi @quanc !

The `:size` attribute won't allow you to use a percentage. There are two reasons for this:

1. QR codes must be square. If you were to set a percentage, it could mess up the 1:1 aspect ratio. I could add some extra CSS to the component so that the QR code maintains the aspect ratio, but I aim to keep it as lightweight as possible.
2. The `:size` attribute sets the width and height for the element in HTML using pixel units. This allows the browsers to allocate the necessary space for the image before the javascript has loaded, preventing layout shift.


On the other hand, your question is if there is a way to use a percentage to set the size of the QR code. Sure there is!

Just add any `id` or `class` to your component:

```html
<qr-code id="my-qrcode" text="Hello World!"></qr-code>
<qr-code class="my-qrcode" text="Hello World!"></qr-code> 
```

And then use some CSS code referencing this `id` or `class` to style it as you want.

Best regards,
Gerard
