### ISSUE TITLE
Question: Can I generate Down Event???

### ISSUE THREAD

**Issue by edgarSang** [gerardreches/vue-qrcode-component#6]
Hello

I m edgar.

I'm using this module well. thank you.

and I have a question.

Can I generate download event?

**Comment by edgarSang** [comment]
when I click button I wanna download this qrcode

**Comment by gerardreches** [comment]
Hi @edgarSang , sorry for the late reply. Actually you can download the QR code as an image like any other image on the web: `mouse right click > Save image as...`

I can't imagine enough use cases to add your request to the component since it's already downloadable using the browser default right click (or hold tap on mobile). If you really need this, you can add a download link wrapper to the component.

```
<a href="#" onclick="this.href = this.getElementsByTagName('img')[0].src;" download>
    <qr-code text="Hello World!"></qr-code> 
</a>
```
