### ISSUE TITLE
props size='116' is not right but :size='116'

### ISSUE THREAD

**Issue by ExiaGo** [gerardreches/vue-qrcode-component#7]
I want to resize the default size for my QR code, so I use the component like this 
`<VueQRCodeComponent :text='QRcodeUrl' size='116' class='QRcodeComponent'></VueQRCodeComponent>`

But the console will show 'Invalid prop: type check failed for prop "size". Expected Number, got String.'
Then I change to this
`<VueQRCodeComponent :text='QRcodeUrl' :size='116' class='QRcodeComponent'></VueQRCodeComponent>`

Now the console not warn.

Although above all can effective, but I think maybe that is a bug?
thank you.

**Comment by gerardreches** [comment]
Welcome @ExiaGo 

I'm trying to reproduce the error, but it's working for me in all possible formats:

```
size="116"
size=116
:size="116"
:size=116
```

Which Vue version are you using?

And by the way, is it just a console warning or a console error? Does the component not work when you get the console message?

Thanks,
Gerard

**Comment by ExiaGo** [comment]
hello @gerardreches 
my Vue version is 2.5.2.
Actually the component is working , and it is a console warning.
I show you my code 
```
import VueQRCodeComponent from 'vue-qrcode-component'
<div class="QRcodeComponentContainer">
        <VueQRCodeComponent :text='QRcodeUrl' :size='116' class='QRcodeComponent'></VueQRCodeComponent>
</div>
```
above that the console will not warning or show any error.
I am happy you can replay me. Thank you.

**Comment by gerardreches** [comment]
As it is stated in the [Vue docs](https://vuejs.org/v2/guide/components-props.html#Passing-a-Number), static numbers passed as props require to be used with `v-bind`:
```html
# Passing a Number

<!-- Even though `42` is static, we need v-bind to tell Vue that -->
<!-- this is a JavaScript expression rather than a string.       -->
<blog-post v-bind:likes="42"></blog-post>
```
So yeah, your code is correct now. Vue was giving you a warning before because of this.

Maybe I didn't detect it because it's a new Vue check (my env was v2.3.3) or because I had the warnings deactivated.

So this must be correctly represented in this [component docs](https://gerardreches.github.io/vue-qrcode-component/). I will correct it in brief.

Thanks for the report @ExiaGo !
